### ISSUE TITLE
Error al consultar un comprobante

### ISSUE THREAD

**Issue by OD-n** [giansalex/sufel-angular#129]
Obtengo el siguiente mensaje de error al querer consultar un comprobante, ya lo he subido, se puede ver el archivo en el API, en la base de datos pero no se logra entrar
![Anotación 2019-07-16 170621](https://user-images.githubusercontent.com/28074529/61333403-70512f80-a7ec-11e9-89de-9d010146c24e.png)

**Comment by giansalex** [comment]
Hola, puedes ingresar a esa url directamante en el navegador?

**Comment by OD-n** [comment]
Hola @giansalex , efecivamente, No, no puedo ingresar a esa URL, la configuración que hice fue en el endpoint de enviroment
![Anotación 2019-07-16 170621](https://user-images.githubusercontent.com/28074529/61337671-1193b200-a7fc-11e9-82f2-35a992f2ddc0.png)

**Comment by giansalex** [comment]
Pero si no puedes ingresar, entonces debes corregir ese problema en el servidor

**Comment by OD-n** [comment]
Okay, voy a ver por que razón puede ser que no puedo ingresar a esa la sección de la API, al dominio puedo ingresar normal, así que voy a ver que podría ser, muchas gracias 👍

**Comment by giansalex** [comment]
Tu endpoint deberia ser `http://apicomsult.estelarsoft.com/public`

**Comment by OD-n** [comment]
Todo está bien, se me olvido, pero el endpoint estaba mal:
no era: http://apicomsult.estelarsoft.com
sino que tenia que colocarse: http://apicomsult.estelarsoft.com/public/
Por si alguien mas se topa con ello.
gracias @giansalex

**Comment by OD-n** [comment]
> Tu punto final deberia ser `http://apicomsult.estelarsoft.com/public`

Disculpa @giansalex . Podrías quitar por favor el link... es por temas de seguridad, se me fue, muchas gracias.

**Comment by giansalex** [comment]
Ok
