### ISSUE TITLE
No busca comprobantes con decimales

### ISSUE THREAD

**Issue by OD-n** [giansalex/sufel-angular#130]
Cuando intento buscar un comprobante individual, y quiero verlo por consulta individual me marca como no encontrado cuando el total del comprobante es con decimales, al parecer en la búsqueda redondea ese monto, como podría hacer para que no lo haga, o donde tengo que modificar?
Espero alguna respuesta, gracias

**Comment by giansalex** [comment]
Hola, no se hace redondeo, podrias revisar que valor se envia, abriendo la consola del navegador > Network

**Comment by OD-n** [comment]
Tienes razón, no redondea, seguiré buscando, solo me pasa eso al consultar documentos con montos que tengan xx.99, xx.98
 o xx.01

![1](https://user-images.githubusercontent.com/28074529/61421118-4884c900-a8cb-11e9-9bfb-c6709671d399.png)
![2](https://user-images.githubusercontent.com/28074529/61421124-4b7fb980-a8cb-11e9-92f7-cd415dab341f.png)

tendría que ver que el xml se genere con mas decimales quiza?, muchas gracias de todos modos, sigo probando subiendo diferentes xml, gracias

**Comment by giansalex** [comment]
talvez el doble slash entre public y api,
Tu endpoint debería terminar en `../public`

**Comment by giansalex** [comment]
Existía un problema por el tipo de dato del campo total en la BD,  podrías cambiarlo de float a double y ver si pasa.

**Comment by OD-n** [comment]
Al cambiar el tipo de dato como ejemplo me cambió el monto de un comprobante de: "599.99" a "599.989990234375"; cabe mencionar que ingresando ese total tampoco me muestra el mismo mensaje de documento no encontrado; podrías darme una breve explicación de como calcula ese monto?, 

El xml generado se calcula con 2 decimales, tanto para los totales como para el precio de los items, quisiera saber si el total que llena en la DB lo toma como el total del xml que subimos, o hace un calculo de los items; no sé si me dejo entender, muchas gracias por la información del tipo de dató, por ello mi pregunta del cálculo del total.

**Comment by giansalex** [comment]
La información del xml no se altera bajo ninguna circunstancia, se guarda tal cual ha sido registrado en el comprobante.

**Comment by giansalex** [comment]
No se hace ningún cálculo, se guarda el monto tal cual esta en el XML

**Comment by OD-n** [comment]
Probé redondear a 2 decimales antes de hacer el INSERT en la DB, asi que cambié la función:
`public function setTotal($total)
    {
        return $this;
    }`

por: 

`public function setTotal($total)
    {
        $this->total = round($total, 2);
        return $this;
    }`

para que en la DB me guarde el monto en redondeado a 2 decimales, como mi sistema trabaja a 2 decimales no hay problema, no podría ser una solución cuando se entregen comprobantes con 3 decimales o mas.
Muchas gracias por la ayuda, no es lo optimo pero por el momento me funcionará, claro que necesitaré buscar la forma de hacer que funcione con otros decimales

**Comment by giansalex** [comment]
No creo que tengas hacer eso, en el XML solo se debería enviar el total con un máximo de 2 decimales según la documentación de SUNAT.

**Comment by OD-n** [comment]
Exacto, el xml que se genera lo hago con LYCET y lo genera con 2 decimales, asi que no podría ser ese el problema, es por ello que no entiendo que guarde en la DB algo por ejemplo:
de 4547.03 que aparece en el xml guarde -> 4547.03254867; como dices, el tipo de dato puede que tenga que ver, pero aún no lo veo tan claro; si consigo algo lo estaré publicando por aqui, muchas gracias.

**Comment by giansalex** [comment]
Hola @OD-n , revise el caso. El problema si era el tipo de dato, y para que no te guarde con decimales extra, debes definirlo con maximo 2 decimales `DOUBLE (10,2)`

Cambio hecho en https://github.com/giansalex/sufel-rest/commit/f5d7a1f6b9b3be22aca6fafafddec5bfc7d27f79
