### ISSUE TITLE
Implementar con servidor api sufel

### ISSUE THREAD

**Issue by yersey20037** [giansalex/sufel-angular#175]
disculpa, que archivo debo modificar para unir este proyecto con la api de sufel en mi hosting

Gracias 
Saludos

**Comment by giansalex** [comment]
Si utilizas un hosting genérico de php debe trabajar con Apache como webserver, en ese caso tendrias que hacer lo siguiente.
- Configurar las url (apuntando a la url del api) y demas en `src/environments/environment.prod.ts`
- Generar el publicado de Angular: `ng build --prod --aot`, esto incluye el `.htaccess` configurado.
- Subes el publicado a la raiz de tu sitio donde se encuentra el API

**Comment by yersey20037** [comment]
este proyecto no incluye la parte para subir archivos verdad?

**Comment by yersey20037** [comment]
es necesario llenar todos los campos :
`
export const environment = {
  production: true,
  ruc: 'No se que poner aqui',(es obligatorio?)
  endpoint= 'http://mipagina.com/sufel/public/',
  company: 'MyCompany',
  companyUrl: 'http://mypagina.com',
  product: 'SUFEL',
  logo: '../assets/img/invoice.png',
};
`
esto es correcto?

**Comment by giansalex** [comment]
lo principal es el endpoint, el ruc es del emisor de los comprobantes si se deja vacio se tendrá que ingresar en el formulario.

**Comment by yersey20037** [comment]
ok
si no pongo el ruc puede ser multiempresa 
utilizar la misma pagina para varios emisores?

**Comment by yersey20037** [comment]
tengo la duda del USUARIO SOL al crear una cuenta de cliente
como hace la validacion de este usuario porque para hacer las pruebas no conosco el usuario sol de los clientes y a todo lo que pongo me dice que no es correcto el nombre

**Comment by giansalex** [comment]
Se usa esta pagina http://www.sunat.gob.pe/cl-ti-itestadousr/usrS00Alias

**Comment by yersey20037** [comment]
Y lo de que puede ser multiempresa es posible?

**Comment by yersey20037** [comment]
o es necesario una pagina diferente para cada emisor?

**Comment by giansalex** [comment]
de por si es multiempresa

**Comment by yersey20037** [comment]
Gracias ya lo subí
Dime y qué puedo utilizar para subirle los archivos automáticamente

**Comment by giansalex** [comment]
Existe en la seccion company, las url para enviar los archivos, de modo que puedes programar el envio automatico al api

**Comment by yersey20037** [comment]
Y puedo usar Sufel Net Sync para subir los archivos
https://github.com/giansalex/sufel-net-sync
O no es para eso?

**Comment by giansalex** [comment]
Si es para eso

**Comment by yersey20037** [comment]
gracias
