### ISSUE TITLE
No se permite buscar documento individual con decimales

### ISSUE THREAD

**Issue by yersey20037** [giansalex/sufel-angular#178]
Buenas noches Giansalex, al querer hacer una busqueda individual de un documento ingresando en el total un numero con punto decimal se marca en rojo el input-text y no permite ejecujar la busqueda.

**Comment by giansalex** [comment]
Hola, tal vez se debe a la configuración regional de la computadora. De otro modo se podría cambiar el type al input

**Comment by yersey20037** [comment]
probe en varias computadoras y encuentro que no permite hacer la busqueda con el campo TOTAL conteniendo punto decimal solo con el navegador Mozilla firefox.

![imagen](https://user-images.githubusercontent.com/56704596/68138673-ecd06100-fef6-11e9-8567-9880c668629d.png)

pero tambien encontre que en ningun navegador encuentra el documento si el total contiene punto decimal me devuelve documento no encontrado. para cualquier documento que contenga punto decimal.

![imagen](https://user-images.githubusercontent.com/56704596/68138984-61a39b00-fef7-11e9-9f88-69b44089e4e1.png)

![imagen](https://user-images.githubusercontent.com/56704596/68139132-9ca5ce80-fef7-11e9-8024-513f71f12b21.png)

**Comment by yersey20037** [comment]
este es el mensaje que devuelve la consola al llamar a un documento con punto decimal

![imagen](https://user-images.githubusercontent.com/56704596/68145686-5acf5500-ff04-11e9-8ce2-d2ac965978f5.png)

**Comment by giansalex** [comment]
Lo ultimo se debe a que el campo debia ser `DOUBLE(10, 2)`; podrias [actualizarlo](https://github.com/giansalex/sufel/blob/master/schema/schema.sql#L25)

**Comment by yersey20037** [comment]
Ok, se corrigio con lo indicado y lo primero lo corregi quitandole el campo number a total.

**Comment by giansalex** [comment]
Si es lo correcto, también realizaré ese cambio
