### ISSUE TITLE
Error al buscar documento individual de dia 31

### ISSUE THREAD

**Issue by yersey20037** [giansalex/sufel-angular#201]
Buenas noches Giansalex, ya tengo el sistema trabajando en produccion y todo funciona bien pero al pasar de los  dias y ir consultando comprobantes encontre que los que pertenecen a una fecha del dia 31 sin importar el mes por ejemplo 31 de enero, 31 de diciembre, 31 de octubre ....
en lugar de mostrarme los datos principales del documento consultado en pantalla me muestra datos de un archivo diferente sin embargo el XML y PDF si son los que corresponden pero con el nombre de otro documento diferente al consultado.
y por ultimo al probar en 2 servidores diferentes y los exploradores 
chrome, firefox y IE. me paso en todos pero al usar un celular o el modo responsive de chome lo muestra correctamente????
 esto si me confundio. podrias decirme si el sistema sufel-angular tiene alguna resticcion de solo 30 dias o que al ser consultado con una resolucion mayor a la de un celular muestra otros datos.
espero poder colaborar a este proyecto tan bueno que compartes con nosotros mostrando los posibles bugs que encontremos para que se haga mas solido.

**Comment by giansalex** [comment]
Hola @yersey20037, no hay tales restricciones.
Y los datos del archivo diferente a que fecha pertenecen, o te refieres al nombre del archivo al momento de guardar?

**Comment by yersey20037** [comment]
Giansalex, los documentos se guardan bien cada uno uno con su fecha correcta tanto en base de datos como en los archivos zip. Al hacer la consulta de un documento del día 31 me muestra los datos del último archivo subido que no sea del día 31 por ejemplo el día 31 de enero al buscar un documento del día 31 me devolvía el último documento subido del día 30 de enero y cuando hago una búsqueda el 1 de febrero de un archivo con fecha 31 de enero me devuelve los datos del último archivo subido el día 1 de febrero en pocas palabras me devuelve el nombre del último archivo subido.
Incluso probé cambiando la fecha en la base de datos al archivo del día 31 le puse 30 y me lo mostró correctamente al hacer la búsqueda como día 30 y un archivo del día 30 que se muestra corrrectamente al buscarlo como 30 le puse 31 en la base datos y al hacer la búsqueda como 31 me muestra datos del último del día 30.
Pero tener en cuenta que esto solo pasa cuando hago la consulta desde una pc porque si lo hago desde un celular o en modo responsive desde chrome me muestra los datos correctos.
Podrías hacer las pruebas para que lo notes tú mismo.
Así que el caso se limita a porque en modo pantalla completa si hace bien la búsqueda pero al hacerlo con pantalla grande no lo hace.
Saludos

**Comment by giansalex** [comment]
Tal como lo explicas, probablemente indique que el problema esta en la data que se envía desde el navegador, podrías revisar que fecha se esta enviando, abriendo la consola del navegador y seleccionando el tap de `Network` (antes de hacer la consulta).

**Comment by yersey20037** [comment]
La fecha enviada es la correcta, es por eso que él navegador devuelve el documento correcto en el pdf y xml pero visualmente en pantalla muestra los datos de otro documento

**Comment by yersey20037** [comment]
Puedo enviarte la data con la que estoy trabajando para que puedas recrear el ambiente y el caso en mención
A qué correo puedo enviártelo internamente para que lo compruebes.
Ya que de manera pública aquí no puedo colgar la data

**Comment by giansalex** [comment]
Ok, este es giansalex@gmail.com

**Comment by giansalex** [comment]
El problema fue aparentemente del lado del servidor, que mantenía en cache la respuesta de una previa consulta, devolviendo resultados inesperados.
