### ISSUE TITLE
consulta

### ISSUE THREAD

**Issue by abelnexus** [giansalex/sufel-angular#4]
amigo me puedes pasar 1 item que este subido en sufel-angular para consultar y ver su funcionamiento por favor
![captura](https://user-images.githubusercontent.com/34687414/37658730-374e5f20-2c1c-11e8-9933-f04fafb5c649.PNG)

**Comment by giansalex** [comment]
esta es la parte cliente, actualmente no esta enlazado a ningún servidor, de modo que no se podrá consultar.
