### ISSUE TITLE
No descarga xml y pdf

### ISSUE THREAD

**Issue by eilsongithub** [giansalex/sufel-angular#68]
Al presionar  sobre los botones de descargar sale un error según la foto y no descarga, Esto es en la consulta individual. en consultas por empresa va bien ...
Ayudenme por favor ... 

![captura](https://user-images.githubusercontent.com/44086967/52783031-92b50600-301e-11e9-89ee-b3eb0efcdfef.JPG)
![error](https://user-images.githubusercontent.com/44086967/52783036-96488d00-301e-11e9-8182-92a0ae977cf9.JPG)

**Comment by giansalex** [comment]
El problema es por el snackbar, podrias comentar esta linea https://github.com/giansalex/sufel-angular/blob/1583a4a25a8e99f7e97a59343bd862f9c5240792/src/app/document/containers/document/document.component.ts#L35
mientras se encuentra una solución.
> Comenta tambien en la llamada de PDF

**Comment by giansalex** [comment]
Hola @eilsongithub , el problema fue solucionado, al parecer existe un conflicto entre angular/material y nebular.
